### ISSUE TITLE
Top NavBar(상단 navbar) 기능 요청

### ISSUE THREAD

**Issue by minzyee** [love-work-club/README#19]
## 기능 요청사항
- [x] 페이지 상단에 위치한 navbar에 대한 마크업 및 스타일 작업

## 요청 세부 사항
- [x] 리액트로 작성
- [ ] 아토믹 디자인 패턴으로 컴포넌트 분리

## 특이사항
- atoms 폴더에 5개의 폴더를 나누어야할까요?
<img width="526" alt="image" src="https://user-images.githubusercontent.com/91003855/207633906-98630ce8-f205-4bed-a7e5-b15b4911d4cc.png">

**Comment by baeggoose** [comment]
📝 Description

- [ ] 기능 추가 : 
- [ ] 스타일 :
- [ ] 리팩토링 :
- [x] 문서 수정 : Baic => Basic 오기 수정했습니다
- [ ] 버그 수정 :
- [ ] 기타 : 

💽 Commits

[Modify] TopNavBarBasic 오기입 수정

## 🎈 Issue Number
close : #19
